DROP SCHEMA SPICEBOYS CASCADE;
CREATE SCHEMA SPICEBOYS;
DROP TABLE IF EXISTS USERS CASCADE;
CREATE  TABLE SPICEBOYS.USERS
(   USR_USER_ID         bigint ,
    USR_FIRST_NAME      varchar,
    USR_LAST_NAME       varchar,
    USR_ADDRESS         varchar,
    USR_STATE           varchar,
    USR_ZIP_CODE        bigint,
    USR_PHONE           bigint,
    USR_EMAIL           varchar
  )
;

DROP TABLE IF EXISTS WEB_EVENTS CASCADE;
CREATE  TABLE SPICEBOYS.WEB_EVENTS
(   WEV_TIMESTAMP       timestamp,
    WEV_EVENT_ID        varchar ,
    WEV_USER_ID         bigint,
    WEV_USER_ORIG_IP    varchar,
    WEV_USER_BROWSER    varchar,
    WEV_NUM_BYTES       bigint,
    WEV_HTTP_COMMAND    varchar,
    WEV_STATUS          varchar,
    WEV_REFERRING_URL    varchar
  )
;

DROP TABLE IF EXISTS PRODUCT CASCADE;

CREATE TABLE SPICEBOYS.PRODUCT(
    P_NAME VARCHAR,
    P_PRODUCT_ID BIGINT ,
    P_DESCRIPTION VARCHAR,
    P_CATEGORY BIGINT,
    P_PRICE BIGINT,
    P_MARGINAL_COST BIGINT,
    P_MANUFACTURER_ID BIGINT,
    P_WEIGHT BIGINT)
;

DROP TABLE IF EXISTS ORDERS CASCADE;

CREATE TABLE SPICEBOYS.ORDERS(
    O_ORDER_ID BIGINT,
    O_USER_ID BIGINT,
    O_TMSTMP TIMESTAMP 
)
;

DROP TABLE IF EXISTS ORDER_DETAILS CASCADE;

CREATE TABLE SPICEBOYS.ORDER_DETAILS(
    OD_ORDER_ID BIGINT,
    OD_PRODUCT_ID BIGINT,
    OD_QUANTITY BIGINT
)
;
